"""Deterministic domain-spec helpers.

The model-driven Role A/Role B flow can replace or refine this output. These
helpers give the CLI a runnable fallback for the hackathon path.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from dataroot.kb.base import DocumentRecord
from dataroot.kb.markdown import record_to_markdown


@dataclass
class DomainSpecSummary:
    output_path: Path
    entities: int
    relationships: int


@dataclass
class ApplyDomainSummary:
    updated_docs: int


def infer_domain_spec(store, output_path: Path) -> DomainSpecSummary:
    records = store.list()
    tables = [record for record in records if record.doc_type == "table"]
    columns = [record for record in records if record.doc_type == "column"]

    columns_by_table: dict[str, list] = {}
    for column in columns:
        columns_by_table.setdefault(str(column.frontmatter.get("table", "")), []).append(column)

    entities = []
    important_columns = []
    aliases = {}
    units = {}

    for table in tables:
        table_columns = columns_by_table.get(table.slug, [])
        key_column = _pick_key_column(table_columns)
        entity_name = _entity_name(table.title)
        entities.append(
            {
                "name": entity_name,
                "description": f"Entity inferred from {table.slug}",
                "maps_from": {
                    "table": table.slug,
                    "key_column": key_column.slug if key_column else None,
                },
            }
        )
        for column in table_columns:
            name = str(column.frontmatter.get("name", column.title))
            if column.frontmatter.get("is_likely_measurement") or column.frontmatter.get("is_likely_fk"):
                important_columns.append(column.slug)
            aliases[name] = sorted(set([name, name.lower(), name.replace("_", " ")]))
            unit = column.frontmatter.get("unit")
            if unit:
                units.setdefault(str(unit), []).append(column.slug)

    relationships = _infer_column_relationships(columns)
    spec = {
        "domain_name": output_path.parent.parent.name if output_path.parent.parent.name else "DataRoot workspace",
        "entities": entities,
        "relationships": relationships,
        "important_columns": sorted(set(important_columns)),
        "aliases": aliases,
        "units": units,
        "traversal_hints": [
            "Start with table and row_group documents, then traverse relationship documents for repeated IDs.",
            "Use measurement columns for threshold questions and row_group documents for cited row-level evidence.",
        ],
        "review_warnings": [
            "Generated by deterministic fallback; review before apply-domain for production use."
        ],
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(spec, indent=2), encoding="utf-8")
    store.write(_domain_spec_record("domain_specs/generated", "Generated Domain Spec", spec, status="generated"))
    store.commit("Write generated domain spec")
    return DomainSpecSummary(output_path=output_path, entities=len(entities), relationships=len(relationships))


def apply_domain_spec(store, spec_path: Path) -> ApplyDomainSummary:
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    store.write(_domain_spec_record("domain_specs/accepted", "Accepted Domain Spec", spec, status="accepted"))
    entity_by_table = {
        entity["maps_from"]["table"]: entity["name"]
        for entity in spec.get("entities", [])
        if entity.get("maps_from", {}).get("table")
    }
    aliases = spec.get("aliases", {})

    updates = 0
    for record in store.list():
        changed = False
        if record.slug in entity_by_table:
            record.frontmatter["domain_entity"] = entity_by_table[record.slug]
            record.frontmatter["domain_tags"] = sorted(set(record.frontmatter.get("domain_tags", []) + [entity_by_table[record.slug]]))
            changed = True
        if record.doc_type == "column":
            name = str(record.frontmatter.get("name", ""))
            if name in aliases:
                record.frontmatter["aliases"] = aliases[name]
                changed = True
        if changed:
            store.update(record.slug, record_to_markdown(record))
            updates += 1

    store.commit("Apply DataRoot domain spec")
    return ApplyDomainSummary(updated_docs=updates)


def _domain_spec_record(slug: str, title: str, spec: dict, status: str) -> DocumentRecord:
    return DocumentRecord(
        doc_type="domain_spec",
        slug=slug,
        title=title,
        frontmatter={
            "status": status,
            "domain_name": spec.get("domain_name"),
            "entity_count": len(spec.get("entities", [])),
            "relationship_count": len(spec.get("relationships", [])),
        },
        body="\n".join(["# " + title, "", "```json", json.dumps(spec, indent=2, default=str), "```"]),
    )


def _pick_key_column(columns: list):
    for column in columns:
        if column.frontmatter.get("is_likely_pk"):
            return column
    for column in columns:
        name = str(column.frontmatter.get("name", "")).lower()
        if name == "id" or name.endswith("_id"):
            return column
    return columns[0] if columns else None


def _entity_name(title: str) -> str:
    name = Path(title).stem.lower()
    return name.replace("-", "_").replace(" ", "_")


def _infer_column_relationships(columns: list) -> list[dict]:
    relationships = []
    seen = set()
    for source in columns:
        source_name = source.frontmatter.get("name")
        source_values = set(str(value) for value in source.frontmatter.get("sample_values", []) if value)
        for target in columns:
            if source.slug >= target.slug:
                continue
            if source_name != target.frontmatter.get("name"):
                continue
            target_values = set(str(value) for value in target.frontmatter.get("sample_values", []) if value)
            overlap = source_values & target_values
            if not overlap:
                continue
            key = tuple(sorted([source.slug, target.slug]))
            if key in seen:
                continue
            seen.add(key)
            relationships.append(
                {
                    "from": source.slug,
                    "to": target.slug,
                    "type": "shared_identifier",
                    "confidence": 0.8 if len(overlap) >= 2 else 0.6,
                    "review_warnings": [] if len(overlap) >= 2 else ["low sample overlap"],
                }
            )
    return relationships
